import type { Tarefa, Meta } from '@/types';
import { format, addDays, subDays } from 'date-fns';

export function generateDemoData(userId: string): { tarefas: Tarefa[]; metas: Meta[] } {
  const today = new Date();
  const fmt = (d: Date) => format(d, 'yyyy-MM-dd');

  const tarefas: Tarefa[] = [
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Lista de exercícios de Álgebra',
      descricao: 'Resolver os exercícios da página 45 a 50 do livro de Matemática sobre equações do 2º grau.',
      disciplina: 'Matemática',
      prazo: fmt(addDays(today, 3)),
      status: 'pendente',
      prioridade: 'alta',
      data_criacao: fmt(today),
      created_at: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Redação: Meio Ambiente',
      descricao: 'Escrever redação argumentativa sobre sustentabilidade e preservação do meio ambiente. Mínimo 30 linhas.',
      disciplina: 'Português',
      prazo: fmt(addDays(today, 5)),
      status: 'pendente',
      prioridade: 'alta',
      data_criacao: fmt(subDays(today, 1)),
      created_at: subDays(today, 1).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Trabalho sobre a Segunda Guerra Mundial',
      descricao: 'Pesquisa e apresentação sobre as causas e consequências da Segunda Guerra Mundial. Slides inclusos.',
      disciplina: 'História',
      prazo: fmt(addDays(today, 7)),
      status: 'pendente',
      prioridade: 'media',
      data_criacao: fmt(subDays(today, 2)),
      created_at: subDays(today, 2).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Mapa geopolítico da América do Sul',
      descricao: 'Criar mapa detalhado com capitais, principais rios e cadeias montanhosas da América do Sul.',
      disciplina: 'Geografia',
      prazo: fmt(addDays(today, 2)),
      status: 'pendente',
      prioridade: 'media',
      data_criacao: fmt(subDays(today, 1)),
      created_at: subDays(today, 1).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Relatório de experimento: Reações Químicas',
      descricao: 'Documentar os resultados do experimento de reações ácido-base realizado em laboratório.',
      disciplina: 'Química',
      prazo: fmt(addDays(today, 10)),
      status: 'pendente',
      prioridade: 'baixa',
      data_criacao: fmt(subDays(today, 3)),
      created_at: subDays(today, 3).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Exercícios de Gramática',
      descricao: 'Concluir os exercícios de morfologia e sintaxe do caderno de atividades.',
      disciplina: 'Português',
      prazo: fmt(subDays(today, 1)),
      status: 'atrasada',
      prioridade: 'alta',
      data_criacao: fmt(subDays(today, 5)),
      created_at: subDays(today, 5).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Prova de Biologia – Células',
      descricao: 'Estudar os capítulos 3 e 4 sobre a estrutura e divisão celular para a prova.',
      disciplina: 'Biologia',
      prazo: fmt(addDays(today, 4)),
      status: 'pendente',
      prioridade: 'alta',
      data_criacao: fmt(today),
      created_at: today.toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Listening – Unit 5',
      descricao: 'Realizar as atividades de listening do livro de inglês, unidade 5.',
      disciplina: 'Inglês',
      prazo: fmt(addDays(today, 8)),
      status: 'concluida',
      prioridade: 'baixa',
      data_criacao: fmt(subDays(today, 4)),
      created_at: subDays(today, 4).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Problemas de Cinemática',
      descricao: 'Resolver lista de problemas de MRU e MRUV – páginas 78 a 82.',
      disciplina: 'Física',
      prazo: fmt(addDays(today, 6)),
      status: 'pendente',
      prioridade: 'media',
      data_criacao: fmt(subDays(today, 2)),
      created_at: subDays(today, 2).toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      titulo: 'Revisão de Frações e Percentuais',
      descricao: 'Revisar frações, números decimais e porcentagem para a prova bimestral.',
      disciplina: 'Matemática',
      prazo: fmt(addDays(today, 1)),
      status: 'concluida',
      prioridade: 'media',
      data_criacao: fmt(subDays(today, 6)),
      created_at: subDays(today, 6).toISOString(),
    },
  ];

  const metas: Meta[] = [
    {
      id: crypto.randomUUID(),
      user_id: userId,
      tipo: 'semanal',
      descricao: 'Concluir 5 tarefas por semana',
      meta_tarefas: 5,
      progresso: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      tipo: 'mensal',
      descricao: 'Finalizar 20 atividades este mês',
      meta_tarefas: 20,
      progresso: 8,
      created_at: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      user_id: userId,
      tipo: 'semanal',
      descricao: 'Estudar Matemática todos os dias',
      meta_tarefas: 7,
      progresso: 3,
      created_at: new Date().toISOString(),
    },
  ];

  return { tarefas, metas };
}
